### ISSUE TITLE
[BUG] Pipeline command not working

### ISSUE THREAD

**Issue by kirianguiller** [oscar-corpus/ungoliant#41]
**Describe the bug**
I have the downloaded CC files in a .../download folder but when I run the pipeline command, I get the following error
```
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**To Reproduce**
1. Have ungoliant installed
2. Have the downloaded n.txt.gz in a folder (where n are the different files "id". I have from 5 to 34)
3. Create a destination folder for where the processed files will be saved
4. Run `ungoliant pipeline /path/to/1_downloaded/ /path/to/ungoliant/ --lid-path /path/to/lid.176.bin`

**Expected behaviour**
Command working fine

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - 
Thanks you a lot :)

**Comment by Uinelj** [comment]
Hello and thank you for the report.
I pushed a fix into the `master` branch that should resolve your issue.

Sorry for the issues, the software is still a bit early in its development and the UI needs polishing. I'll rework the IO error reporting soon.

Let me know if the fix works for you and if it does I'll close the issue.

**Comment by kirianguiller** [comment]
Alright, thanks a lot !

Now when I try to run the pipeline, I get the following (long) error :
```bash
ungoliant pipeline /gazelle/corpora/ungoliant/1_download/ /gazelle/corpora/ungoliant/2_pipeline --lid-path /root/projects/ungoliant-dioco/lid.176.bin
```

```
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/25795.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/21897.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/27335.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/11642.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/27108.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/19287.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/31374.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/25267.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/19152.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/27512.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/37498.txt.gz"
thread 'thread '[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/35205.txt.gz"
<unnamed><unnamed>' panicked at 'thread 'thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed><unnamed>[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/31553.txt.gz"
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', ' panicked at '' panicked at '', called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))src/transformers/annotate.rs', thread 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))src/transformers/annotate.rs:src/transformers/annotate.rsthread '<unnamed>[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/33226.txt.gz"
', :31::<unnamed>' panicked at 'thread 'src/transformers/annotate.rs313155' panicked at 'thread '[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/23079.txt.gz"
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed>::thread ':
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed>', ', ' panicked at '3155<unnamed>[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/9320.txt.gz"
55note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '' panicked at 'thread '[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/9507.txt.gz"
src/transformers/annotate.rssrc/transformers/annotate.rs:called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))
' panicked at '
thread '<unnamed>called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed>thread '::', called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed>' panicked at '', ' panicked at '<unnamed>3131src/transformers/annotate.rs', thread 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))src/transformers/annotate.rs' panicked at ':::thread ':src/transformers/annotate.rs<unnamed>', called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))5531
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/21531.txt.gz"
55<unnamed>31:' panicked at '', src/transformers/annotate.rs', ::src/transformers/annotate.rsthread '' panicked at '
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))thread ':31called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))src/transformers/annotate.rs31:5531:<unnamed>', <unnamed>55:', [2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/19775.txt.gz"
:
:31' panicked at 'src/transformers/annotate.rs' panicked at '
55src/transformers/annotate.rs5555:called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/35984.txt.gz"
:

55', 31', 31
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/37570.txt.gz"
src/transformers/annotate.rs:src/transformers/annotate.rs:::5555[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/9949.txt.gz"
3131

::5555[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/23191.txt.gz"


[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/21316.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/23463.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/23244.txt.gz"
thread '[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/37357.txt.gz"
<unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))<unnamed>', ' panicked at 'src/transformers/annotate.rscalled `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):', 31src/transformers/annotate.rsthread ':thread ':[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/11065.txt.gz"
thread 'thread '<unnamed>55<unnamed>31<unnamed><unnamed>' panicked at '
' panicked at ':called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))thread 'thread '55', thread 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', ', <unnamed>thread '<unnamed>
src/transformers/annotate.rs<unnamed>', src/transformers/annotate.rssrc/transformers/annotate.rs:' panicked at '<unnamed>' panicked at ':thread '' panicked at 'src/transformers/annotate.rs:31called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))31<unnamed>:31:', called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', ', :src/transformers/annotate.rs' panicked at '31:55src/transformers/annotate.rs', src/transformers/annotate.rs55:called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):55', 
:src/transformers/annotate.rs31:
3155
src/transformers/annotate.rs::31:
:3155:5531:
:55
5555[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/35038.txt.gz"



[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/19548.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/19906.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/35422.txt.gz"
55[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/11597.txt.gz"
src/transformers/annotate.rs
:31[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/25440.txt.gz"
:55
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/37082.txt.gz"
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/33401.txt.gz"
thread '<unnamed>' panicked at '[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/31686.txt.gz"
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', src/transformers/annotate.rs:31:[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/3178.txt.gz"
thread '55thread '<unnamed>
<unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))thread 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', thread '<unnamed>', src/transformers/annotate.rs<unnamed>' panicked at 'src/transformers/annotate.rs:' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):31called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', 31:', src/transformers/annotate.rsthread ':<unnamed>[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/13963.txt.gz"
thread '<unnamed>55' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))src/transformers/annotate.rs
', ::thread 'src/transformers/annotate.rs3131:::thread '<unnamed>3155thread '55:<unnamed>55
<unnamed>
55' panicked at '
' panicked at '
called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', ', ' panicked at 'src/transformers/annotate.rs[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/31149.txt.gz"
src/transformers/annotate.rs:called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):31', 31:src/transformers/annotate.rs:55:55
31
:thread '55<unnamed>
' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', src/transformers/annotate.rs:31:55
' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', thread 'src/transformers/annotate.rs<unnamed>:' panicked at '31called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/")):', 55src/transformers/annotate.rs
:31:55
[2022-03-02T18:00:33Z INFO  ungoliant::pipelines::oscardoc::pipeline] working on shard: "/gazelle/corpora/ungoliant/1_download/1217.txt.gz"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Ut1(NotADirectory("./ut1-blacklists/blacklists/"))', src/transformers/annotate.rs:31:55
```

**Comment by Uinelj** [comment]
Be aware that the new version makes blocklist usage **optional** (we used the aforementioned blocklist in the upcoming OSCAR release).

Let me know if you encounter any other issues, as the software is mainly used internally there still is some errors that we haven't fixed.

**Comment by kirianguiller** [comment]
Ok thanks ! Working correctly now :)
